Document: handle-core
Title: Debian handle-core Manual
Author: <insert document author here>
Abstract: This manual describes what handle-core is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/handle-core/handle-core.sgml.gz

Format: postscript
Files: /usr/share/doc/handle-core/handle-core.ps.gz

Format: text
Files: /usr/share/doc/handle-core/handle-core.text.gz

Format: HTML
Index: /usr/share/doc/handle-core/html/index.html
Files: /usr/share/doc/handle-core/html/*.html


